version: 2.1

orbs:
  android: circleci/android@2.5.0

jobs:
  build_and_test:
    docker:
      - image: cimg/android:2026.03.1
    resource_class: large
    steps:
      - checkout
      - run:
          name: Create local.properties
          command: |
            echo "BASE_URL=${BASE_URL}" >> local.properties
            echo "API_KEY=${API_KEY}" >> local.properties

      - android/restore-gradle-cache

      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew

      - run:
          name: Run Quality Check & Build
          command: ./gradlew lintDebug testDebugUnitTest koverHtmlReportDebug assembleDebug bundleDebug --continue

      - run:
          name: Gather Test & Lint Results
          when: always
          command: |
            mkdir -p ~/results/junit/
            mkdir -p ~/results/lint/
            mkdir -p ~/results/coverage/
            
            find . -type d -name "test-results" -exec cp -r {} ~/results/junit/ \;
            find . -type f -name "lint-results-debug.*" -exec cp {} ~/results/lint/ \;
            find . -path "*/build/reports/kover/htmlDebug" -type d -exec cp -r {}/. ~/results/coverage/ \;
            
            if [ -d "build/reports/kover/htmlDebug" ]; then
              echo "Mengambil laporan gabungan dari Root..."
              cp -r build/reports/kover/htmlDebug/* ~/results/coverage/
            else
              mkdir -p ~/results/coverage/app ~/results/coverage/core ~/results/coverage/favorite
              [ -d "app/build/reports/kover/htmlDebug" ] && cp -r app/build/reports/kover/htmlDebug/* ~/results/coverage/app/
              [ -d "core/build/reports/kover/htmlDebug" ] && cp -r core/build/reports/kover/htmlDebug/* ~/results/coverage/core/
              [ -d "favorite/build/reports/kover/htmlDebug" ] && cp -r favorite/build/reports/kover/htmlDebug/* ~/results/coverage/favorite/
            fi

      - store_test_results:
          path: ~/results/junit

      - store_artifacts:
          path: ~/results/coverage
          destination: code-coverage-report

      - store_artifacts:
          path: ~/results/lint
          destination: lint-reports

      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: builds/debug-apk

      - store_artifacts:
          path: app/build/outputs/bundle/debug/
          destination: builds/debug-aab

      - android/save-gradle-cache

workflows:
  main:
    jobs:
      - build_and_test