version: 2.1

orbs:
  android: circleci/android@2.5.0

jobs:
  build:
    docker:
      - image: cimg/android:2026.03.1
    resource_class: large
    steps:
      - checkout
      - run:
          name: Create local.properties
          command: |
            echo "BASE_URL=${BASE_URL}" >> local.properties
            echo "API_KEY=${API_KEY}" >> local.properties

      - android/restore-gradle-cache

      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew

      - run:
          name: Run Lint
          command: ./gradlew lint lintDebug

      - run:
          name: Run Tests and Generate Coverage
          command: ./gradlew koverHtmlReportDebug --continue

      - run:
          name: Run All Debug Unit Tests
          command: ./gradlew testDebugUnitTest --continue

      - run:
          name: Build Debug APK and Bundle
          command: ./gradlew assembleDebug bundleDebug

      - run:
          name: Gather Test & Lint Results
          when: always
          command: |
            mkdir -p ~/results/junit/
            mkdir -p ~/results/lint/
            mkdir -p ~/results/coverage/
            
            find . -type d -name "test-results" -exec cp -r {} ~/results/junit/ \;
            find . -type f -name "lint-results-debug.*" -exec cp {} ~/results/lint/ \;
            cp -r build/reports/kover/htmlDebug/* ~/results/coverage/ || true

      - store_test_results:
          path: ~/results/junit

      - store_artifacts:
          path: ~/results/coverage
          destination: code-coverage-report

      - store_artifacts:
          path: ~/results/lint
          destination: lint-reports

      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: builds/debug-apk

      - store_artifacts:
          path: app/build/outputs/bundle/debug/
          destination: builds/debug-aab

      - android/save-gradle-cache